### ISSUE TITLE
Terrain features

### ISSUE THREAD

**Issue by PhiGei2000** [PhiGei2000/CityBuilderGame#3]
Features
-----
- [x] noise generated terrain height
- [x] generate lakes
- [x] reimplement coordinate transformations and make clear where which coords are used
- [x] procedural terrain generation

**Comment by angelskieglazki** [comment]
What algorithm you will plane to use for procedural terrain generation? Diamod-square?

**Comment by PhiGei2000** [comment]
Currently I'm using Perlin-Noise to generate the terrain height. The library I use is called [libnoise](https://libnoise.sourceforge.net/).

**Comment by angelskieglazki** [comment]
If you need some help - open the issue here :) I'm network programmer. Maybe later we can add client server interaction, for coop  for example
