### ISSUE TITLE
Can't build GLM errors

### ISSUE THREAD

**Issue by Intervel** [PhiGei2000/CityBuilderGame#4]
CMake Error at CMakeLists.txt:30 (find_package):
  By not providing "Findglm.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "glm", but
  CMake did not find one.

  Could not find a package configuration file provided by "glm" with any of
  the following names:

    glmConfig.cmake
    glm-config.cmake

  Add the installation prefix of "glm" to CMAKE_PREFIX_PATH or set "glm_DIR"
  to a directory containing one of the above files.  If "glm" provides a
  separate development package or SDK, be sure it has been installed.

![CMake 3 27 4 - C__CityBuilderGame_build 9_8_2023 5_51_11 PM](https://github.com/PhiGei2000/CityBuilderGame/assets/86478025/9bad6ffe-1479-464e-a606-4074b0bd01de)

please help :(

**Comment by PhiGei2000** [comment]
Check out the development branch. It should work there. The master branch is not up to date.

If you want to stay on the master branch, add the folder containing the glm directory to CMAKE_PREFIX_PATH or put the glm directory in C:\lib

**Comment by Intervel** [comment]
thanks for replying! i will check it out :)
